# **Project Description** :-

This project is about exploring a dataset that lists **chemicals used in cosmetic products**, reported to the California Safe Cosmetics Program. The dataset has details about products, companies, brands, categories, and the chemicals inside them.

The main goal is to study how these chemicals are used, find patterns over time, and discover insights about product safety, company habits, and category behavior. By cleaning and organizing the data, the project aims to convert raw data into meaningful insights.

The first step is data preprocessing — fixing missing values, removing duplicates, and making sure dates are in the right format. **Feature engineering techniques** are applied to extract useful information such as reporting year and product status (active/discontinued).

The project then explores the data using **univariate, bivariate, and multivariate analysis techniques**. Various visualizations such as bar charts, histograms, boxplots, and line charts are used to understand distributions, relationships, and trends.

# **Key areas of analysis** :-
The project mainly looks at:

**Product categories** → How products are spread across different types and subtypes.

**Chemical usage** → Which chemicals are used most often.

**Company and brand activity** → Which companies and brands contribute the most.

**Trends over time** → How chemical usage changes year by year.

**Company practices** → Looking at which companies report more or fewer chemicals.

# **Objectives** :-

**Clean the data** → Fix errors, remove duplicates, and prepare the dataset for analysis.

**Study product and chemical spread** → See how cosmetic products and chemicals are distributed.

**Find trends over time** → Check how chemical usage has changed year by year.

**Evaluate companies and brands** → Look at how different companies and brands are performing.

**Create useful measures (KPIs)** → Build simple numbers to track chemical use, product variety, and company activity.

**Give practical recommendations** → Suggest actions based on findings, like spotting risky categories or safer product trends.

# **Chemicals in Cosmetics Dataset - Data Dictionary** :-

1-**CDPHId**

Unique identifier assigned by the California Department of Public Health (CDPH) for each record

2-**ProductName**

Name of the cosmetic product

3-**CSFId**

Unique ID for the reported product formulation (Cosmetic Safe Formulation ID)

4-**CSF**

Cosmetic formulation name or identifier submitted by the company

5-**CompanyId**

Unique ID assigned to each company

6-**CompanyName**

Name of the company that manufactures or distributes the product

7-**BrandName**

Brand under which the product is sold

8-**PrimaryCategoryId**

ID representing the main category of the cosmetic product

9-**PrimaryCategory**

Main category (e.g., Makeup, Skin Care, Hair Care)

10-**SubCategoryId**

ID representing the sub-category

11-**SubCategory**

Specific product type (e.g., Lipstick, Shampoo, Lotion)

12-**CasId**

Unique identifier for a chemical substance

13-**CasNumber**

CAS number – globally recognized chemical identifier

14-**ChemicalId**

Internal ID assigned to each chemical

15-**ChemicalName**

Name of the chemical present in the product

16-**InitialDateReported**

Date when the product-chemical combination was first reported

17-**MostRecentDateReported**

Latest date when the record was updated or confirmed

18-**DiscontinuedDate**

Date when the product was discontinued (if applicable)

19-**ChemicalCreatedAt**

Timestamp when the chemical record was created

20-**ChemicalUpdatedAt**

Timestamp when the chemical record was last updated

21-**ChemicalDateRemoved**

Date when the chemical was removed from the product (if applicable)

22-**ChemicalCount**

Number of chemicals reported for that product

# **Step 1: Data Loading** :-

In [4]:
# Import the liabraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [5]:
# Connect Google Drive to Google Colab
from google.colab import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google'

In [ ]:
# Data Loading
df=pd.read_csv('/content/drive/MyDrive/Colab Notebooks/cscpopendata.csv')

! Now the data is completely loaded.

# **Step 2 :Data Overview** :-

In [ ]:
# To showing all columns of the dataset
pd.set_option('display.max_columns',None)

In [ ]:
# Checking if the dataset is loaded correctly or not
df.head()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,SubCategory,CasId,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,6,Titanium dioxide,06/17/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
1,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),889,65996-92-1,4,Distillates (coal tar),07/01/2009,07/01/2009,NaN,07/01/2009,07/01/2009,NaN,2
2,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),293,140-67-0,5,Estragole,07/01/2009,07/01/2009,NaN,07/02/2009,07/02/2009,NaN,2
3,4,PRECISION GLIMMER EYE LINER-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),46,Eyeliner/Eyebrow Pencils,656,13463-67-7,7,Titanium dioxide,07/09/2009,08/28/2013,NaN,07/09/2009,07/09/2009,NaN,1
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,Lip Gloss/Shine,656,13463-67-7,8,Titanium dioxide,07/09/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1

In [ ]:
# Checking the end of the dataset
df.tail()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,SubCategory,CasId,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
114630,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,65001.0,Rosa Soft,1259,"Yanbal USA, Inc",YANBAL,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68059,Titanium dioxide,06/19/2020,06/19/2020,NaN,06/19/2020,06/19/2020,NaN,1
114631,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,65002.0,Malva Spirit,1259,"Yanbal USA, Inc",YANBAL,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68060,Titanium dioxide,06/19/2020,06/19/2020,NaN,06/19/2020,06/19/2020,NaN,1
114632,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,65003.0,Rojo Fashion,1259,"Yanbal USA, Inc",YANBAL,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68061,Titanium dioxide,06/19/2020,06/19/2020,NaN,06/19/2020,06/19/2020,NaN,1
114633,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,65004.0,Terra Mystic,1259,"Yanbal USA, Inc",YANBAL,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68062,Titanium dioxide,06/19/2020,06/19/2020,NaN,06/19/2020,06/19/2020,NaN,1
114634,41524,OLD SPICE GENTLEMENS BLEND ALOE AND WILD SAGE ...,NaN,NaN,86,The Procter & Gamble Company,Old Spice,6,Bath Products,159,Body Washes and Soaps,656,13463-67-7,68074,Titanium dioxide,06/23/2020,06/23/2020,NaN,06/23/2020,06/23/2020,NaN,1

In [ ]:
# Check the shape of the dataset
df.shape

(114635, 22)

i.e. there are 114635 rows and 22 columns in the dataset.

In [ ]:
# Checking random subset of your dataset
df.sample(5)

NameError: name 'df' is not defined

In [ ]:
# Find the total columns available in the dataset
print(list(df.columns),end='')

['CDPHId', 'ProductName', 'CSFId', 'CSF', 'CompanyId', 'CompanyName', 'BrandName', 'PrimaryCategoryId', 'PrimaryCategory', 'SubCategoryId', 'SubCategory', 'CasId', 'CasNumber', 'ChemicalId', 'ChemicalName', 'InitialDateReported', 'MostRecentDateReported', 'DiscontinuedDate', 'ChemicalCreatedAt', 'ChemicalUpdatedAt', 'ChemicalDateRemoved', 'ChemicalCount']

In [ ]:
# To check Data Types and Non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 114635 entries, 0 to 114634
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CDPHId                  114635 non-null  int64
 1   ProductName             114635 non-null  object
 2   CSFId                   80662 non-null   float64
 3   CSF                     80237 non-null   object
 4   CompanyId               114635 non-null  int64
 5   CompanyName             114635 non-null  object
 6   BrandName               114408 non-null  object
 7   PrimaryCategoryId       114635 non-null  int64
 8   PrimaryCategory         114635 non-null  object
 9   SubCategoryId           114635 non-null  int64
 10  SubCategory             114635 non-null  object
 11  CasId                   114635 non-null  int64
 12  CasNumber               108159 non-null  object
 13  ChemicalId              114635 non-null  int64
 14  ChemicalName            114635 non-null  object
 15  InitialDateReported     114635 non-null  object
 16  MostRecentDateReported  114635 non-null  object
 17  DiscontinuedDate        12920 non-null   object
 18  ChemicalCreatedAt       114635 non-null  object
 19  ChemicalUpdatedAt       114635 non-null  object
 20  ChemicalDateRemoved     2985 non-null    object
 21  ChemicalCount           114635 non-null  int64
dtypes: float64(1), int64(7), object(14)
memory usage: 19.2+ MB

**Observations in the dataset** ->   One column (CSFId) is numeric but allows decimals (float64).

By default, Pandas reads everything as text (object) unless it clearly looks numeric. So columns like InitialDateReported, MostRecentDateReported, DiscontinuedDate, etc. are just strings right now.

In [ ]:
# Checking description of the dataset
# This gives you a statistical summary of your dataset.
df.describe()

,CDPHId,CSFId,CompanyId,PrimaryCategoryId,SubCategoryId,CasId,ChemicalId,ChemicalCount
count,114635.000000,80662.000000,114635.000000,114635.000000,114635.000000,114635.000000,114635.000000,114635.000000
mean,20304.858987,32608.658377,450.641532,51.076294,66.819252,674.094107,32837.556959,1.288359
std,12489.052554,19089.443910,409.533093,20.474341,35.822097,149.214101,20439.412299,0.636418
min,2.000000,1.000000,4.000000,1.000000,3.000000,2.000000,0.000000,0.000000
25%,8717.000000,15789.000000,86.000000,44.000000,48.000000,656.000000,13990.000000,1.000000
50%,20895.000000,32541.000000,297.000000,44.000000,52.000000,656.000000,32055.000000,1.000000
75%,31338.500000,48717.750000,798.000000,59.000000,65.000000,656.000000,51578.500000,1.000000
max,41524.000000,65009.000000,1391.000000,111.000000,172.000000,1242.000000,68074.000000,9.000000

In [ ]:
# How to drop the duplicate value?
# First we need to create a copy of dataset.
df1=df.copy()

In [ ]:
# Checking duplicated values available in the dataset.
duplicate_values=df1[df1.duplicated()]
print(duplicate_values)

       CDPHId                                        ProductName    CSFId  \
15087    3488       CHI Scentuals Mango Melon Hand and Body Wash      NaN
15094    3494    CHI Scentuals Lavender Latte Hand and Body Wash      NaN
15116    3506      CHI Scentuals Coconut Lime Hand and Body Wash      NaN
15223    3576    CHI Ionic Permanent Shine Hair Color 1N - Black      NaN
15230    3583  CHI Ionic Permanent Shine Hair Color 2N - Natu...      NaN
...       ...                                                ...      ...
54624   19429                                      Cologne Spray  29397.0
54626   19429                                      Cologne Spray  29398.0
82305   29757                                   MATTE REVOLUTION  46432.0
82307   29757                                   MATTE REVOLUTION  46432.0
98497   36193  MEISHOKU Moist-Labo BB Mineral Pressed Powder ...      NaN

                      CSF  CompanyId                      CompanyName  \
15087                 NaN        120             Farouk Systems, Inc.
15094                 NaN        120             Farouk Systems, Inc.
15116                 NaN        120             Farouk Systems, Inc.
15223                 NaN        120             Farouk Systems, Inc.
15230                 NaN        120             Farouk Systems, Inc.
...                   ...        ...                              ...
54624           Pure Soap        887  Demeter Fragrance Library, Inc.
54626                Dirt        887  Demeter Fragrance Library, Inc.
82305  Between the Sheets       1154     Charlotte Tilbury Beauty Ltd
82307  Between the Sheets       1154     Charlotte Tilbury Beauty Ltd
98497                 NaN       1248          MOMOTANI JUNTENKAN LTD.

               BrandName  PrimaryCategoryId                  PrimaryCategory  \
15087                CHI                  6                    Bath Products
15094                CHI                  6                    Bath Products
15116                CHI                  6                    Bath Products
15223                CHI                 32           Hair Coloring Products
15230                CHI                 32           Hair Coloring Products
...                  ...                ...                              ...
54624            Demeter                 12                       Fragrances
54626            Demeter                 12                       Fragrances
82305  Charlotte Tilbury                 44  Makeup Products (non-permanent)
82307  Charlotte Tilbury                 44  Makeup Products (non-permanent)
98497           MEISHOKU                 44  Makeup Products (non-permanent)

       SubCategoryId                                 SubCategory  CasId  \
15087            159                       Body Washes and Soaps   1102
15094            159                       Body Washes and Soaps   1102
15116            159                       Body Washes and Soaps   1102
15223             35                        Hair Dyes and Colors   1102
15230             35                        Hair Dyes and Colors   1102
...              ...                                         ...    ...
54624             13                                     Cologne   1102
54626             13                                     Cologne   1102
82305             53  Lip Color - Lipsticks, Liners, and Pencils    776
82307             53  Lip Color - Lipsticks, Liners, and Pencils    656
98497             49                                Face Powders   1102

        CasNumber  ChemicalId  \
15087           0           0
15094           0           0
15116           0           0
15223           0           0
15230           0           0
...           ...         ...
54624           0           0
54626           0           0
82305         NaN       48169
82307  13463-67-7       48170
98497           0           0

                                            ChemicalName InitialDateReported  \
15087                                       Trade Secret          10/12/2009
15094                                       Trade Secret          10/12/2009
15116                                       Trade Secret          10/12/2009
15223                                       Trade Secret          10/12/2009
15230                                       Trade Secret          10/12/2009
...                                                  ...                 ...
54624                                       Trade Secret          02/04/2013
54626                                       Trade Secret          02/04/2013
82305  Silica, crystalline (airborne particles of res...          03/21/2017
82307                                   Titanium dioxide          03/21/2017
98497                                       Trade Secret          01/16/2019

      MostRecentDateReported DiscontinuedDate ChemicalCreatedAt  \
15087             10/12/2009              NaN        10/12/2009
15094             10/12/2009              NaN        10/12/2009
15116             10/12/2009              NaN        10/12/2009
15223             10/12/2009              NaN        10/12/2009
15230             10/12/2009              NaN        10/12/2009
...                      ...              ...               ...
54624             02/04/2013              NaN        02/04/2013
54626             02/04/2013              NaN        02/04/2013
82305             10/23/2019              NaN        03/21/2017
82307             10/23/2019              NaN        03/21/2017
98497             01/24/2019              NaN        01/24/2019

      ChemicalUpdatedAt ChemicalDateRemoved  ChemicalCount
15087        10/12/2009                 NaN              1
15094        10/12/2009                 NaN              1
15116        10/12/2009                 NaN              1
15223        10/12/2009                 NaN              1
15230        10/12/2009                 NaN              1
...                 ...                 ...            ...
54624        02/04/2013                 NaN              1
54626        02/04/2013                 NaN              1
82305        10/17/2019                 NaN              2
82307        10/17/2019                 NaN              2
98497        01/24/2019                 NaN              1

[254 rows x 22 columns]

In [ ]:
# Droping the all duplicate values.
df1=df1.drop_duplicates()

In [ ]:
#Checking the count of remaining no. of rows/columns).
df1.shape

(114381, 22)

In [ ]:
# Find the null values available in the dataset.
df1.isnull().sum()

CDPHId                         0
ProductName                    0
CSFId                      33731
CSF                        34156
CompanyId                      0
CompanyName                    0
BrandName                    227
PrimaryCategoryId              0
PrimaryCategory                0
SubCategoryId                  0
SubCategory                    0
CasId                          0
CasNumber                   6475
ChemicalId                     0
ChemicalName                   0
InitialDateReported            0
MostRecentDateReported         0
DiscontinuedDate          101508
ChemicalCreatedAt              0
ChemicalUpdatedAt              0
ChemicalDateRemoved       111396
ChemicalCount                  0
dtype: int64

In [ ]:
# Checking the null values in the dataset.
df1.head()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,SubCategory,CasId,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,6,Titanium dioxide,06/17/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
1,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),889,65996-92-1,4,Distillates (coal tar),07/01/2009,07/01/2009,NaN,07/01/2009,07/01/2009,NaN,2
2,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),293,140-67-0,5,Estragole,07/01/2009,07/01/2009,NaN,07/02/2009,07/02/2009,NaN,2
3,4,PRECISION GLIMMER EYE LINER-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),46,Eyeliner/Eyebrow Pencils,656,13463-67-7,7,Titanium dioxide,07/09/2009,08/28/2013,NaN,07/09/2009,07/09/2009,NaN,1
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,Lip Gloss/Shine,656,13463-67-7,8,Titanium dioxide,07/09/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1

In [ ]:
# How to fill the null values.
# First check the unique values in BrandName column.
df1['BrandName'].unique()

array(['AVON', "Glover's", 'OPI', ..., 'sulwhasoo ', 'HAIR FOOD',
       'YANBAL'], dtype=object)

In [ ]:
# Find the mode of the BrandName column.
mode_value=df1['BrandName'].mode()[0]
print(mode_value)

SEPHORA

In [ ]:
# Fill the null values in BrandName column with the mode value.
df1['BrandName']= df1['BrandName'].fillna(mode_value)

In [ ]:
# Checking the null values again in the dataset if BrandName is filled properly.
df1.isnull().sum()

CDPHId                         0
ProductName                    0
CSFId                      33731
CSF                        34156
CompanyId                      0
CompanyName                    0
BrandName                      0
PrimaryCategoryId              0
PrimaryCategory                0
SubCategoryId                  0
SubCategory                    0
CasId                          0
CasNumber                   6475
ChemicalId                     0
ChemicalName                   0
InitialDateReported            0
MostRecentDateReported         0
DiscontinuedDate          101508
ChemicalCreatedAt              0
ChemicalUpdatedAt              0
ChemicalDateRemoved       111396
ChemicalCount                  0
dtype: int64

In [ ]:
# Now Checking the data type of columns. (Which are incorrect)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 114381 entries, 0 to 114634
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CDPHId                  114381 non-null  int64
 1   ProductName             114381 non-null  object
 2   CSFId                   80650 non-null   float64
 3   CSF                     80225 non-null   object
 4   CompanyId               114381 non-null  int64
 5   CompanyName             114381 non-null  object
 6   BrandName               114381 non-null  object
 7   PrimaryCategoryId       114381 non-null  int64
 8   PrimaryCategory         114381 non-null  object
 9   SubCategoryId           114381 non-null  int64
 10  SubCategory             114381 non-null  object
 11  CasId                   114381 non-null  int64
 12  CasNumber               107906 non-null  object
 13  ChemicalId              114381 non-null  int64
 14  ChemicalName            114381 non-null  object
 15  InitialDateReported     114381 non-null  object
 16  MostRecentDateReported  114381 non-null  object
 17  DiscontinuedDate        12873 non-null   object
 18  ChemicalCreatedAt       114381 non-null  object
 19  ChemicalUpdatedAt       114381 non-null  object
 20  ChemicalDateRemoved     2985 non-null    object
 21  ChemicalCount           114381 non-null  int64
dtypes: float64(1), int64(7), object(14)
memory usage: 20.1+ MB

In [ ]:
# Converting the data type of columns. (Which are incorrect)
cols=['InitialDateReported','MostRecentDateReported','DiscontinuedDate','ChemicalCreatedAt','ChemicalUpdatedAt','ChemicalDateRemoved']
for col in cols:
  df1[col]=df1[col].astype('datetime64[ns]')

In [ ]:
# Now again checking the data type of columns. (checking if cols list updated or not)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 114381 entries, 0 to 114634
Data columns (total 22 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   CDPHId                  114381 non-null  int64
 1   ProductName             114381 non-null  object
 2   CSFId                   80650 non-null   float64
 3   CSF                     80225 non-null   object
 4   CompanyId               114381 non-null  int64
 5   CompanyName             114381 non-null  object
 6   BrandName               114381 non-null  object
 7   PrimaryCategoryId       114381 non-null  int64
 8   PrimaryCategory         114381 non-null  object
 9   SubCategoryId           114381 non-null  int64
 10  SubCategory             114381 non-null  object
 11  CasId                   114381 non-null  int64
 12  CasNumber               107906 non-null  object
 13  ChemicalId              114381 non-null  int64
 14  ChemicalName            114381 non-null  object
 15  InitialDateReported     114381 non-null  datetime64[ns]
 16  MostRecentDateReported  114381 non-null  datetime64[ns]
 17  DiscontinuedDate        12873 non-null   datetime64[ns]
 18  ChemicalCreatedAt       114381 non-null  datetime64[ns]
 19  ChemicalUpdatedAt       114381 non-null  datetime64[ns]
 20  ChemicalDateRemoved     2985 non-null    datetime64[ns]
 21  ChemicalCount           114381 non-null  int64
dtypes: datetime64[ns](6), float64(1), int64(7), object(8)
memory usage: 20.1+ MB

In [ ]:
# Creating a new column as Discontinued_Month.
df1['Discontinued_Month']=df1['DiscontinuedDate'].dt.month

In [ ]:
# Dropping unnecessary columns for better analysis.
df1.drop(columns=['CSF','CSFId','CompanyId','PrimaryCategoryId','SubCategoryId'])

,CDPHId,ProductName,CompanyName,BrandName,PrimaryCategory,SubCategory,CasId,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount,Discontinued_Month
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,New Avon LLC,AVON,Makeup Products (non-permanent),"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,6,Titanium dioxide,2009-06-17,2013-08-28,2011-02-01,2009-07-09,2009-07-09,NaT,1,2.0
1,3,Glover's Medicated Shampoo,J. Strickland & Co.,Glover's,Hair Care Products (non-coloring),Hair Shampoos (making a cosmetic claim),889,65996-92-1,4,Distillates (coal tar),2009-07-01,2009-07-01,NaT,2009-07-01,2009-07-01,NaT,2,NaN
2,3,Glover's Medicated Shampoo,J. Strickland & Co.,Glover's,Hair Care Products (non-coloring),Hair Shampoos (making a cosmetic claim),293,140-67-0,5,Estragole,2009-07-01,2009-07-01,NaT,2009-07-02,2009-07-02,NaT,2,NaN
3,4,PRECISION GLIMMER EYE LINER-ALL SHADES �,New Avon LLC,AVON,Makeup Products (non-permanent),Eyeliner/Eyebrow Pencils,656,13463-67-7,7,Titanium dioxide,2009-07-09,2013-08-28,NaT,2009-07-09,2009-07-09,NaT,1,NaN
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,New Avon LLC,AVON,Makeup Products (non-permanent),Lip Gloss/Shine,656,13463-67-7,8,Titanium dioxide,2009-07-09,2013-08-28,2011-02-01,2009-07-09,2009-07-09,NaT,1,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114630,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,"Yanbal USA, Inc",YANBAL,Makeup Products (non-permanent),"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68059,Titanium dioxide,2020-06-19,2020-06-19,NaT,2020-06-19,2020-06-19,NaT,1,NaN
114631,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,"Yanbal USA, Inc",YANBAL,Makeup Products (non-permanent),"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68060,Titanium dioxide,2020-06-19,2020-06-19,NaT,2020-06-19,2020-06-19,NaT,1,NaN
114632,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,"Yanbal USA, Inc",YANBAL,Makeup Products (non-permanent),"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68061,Titanium dioxide,2020-06-19,2020-06-19,NaT,2020-06-19,2020-06-19,NaT,1,NaN
114633,41523,HYDRA-LIP TRANSLUCENT COLOR LIPSTICK,"Yanbal USA, Inc",YANBAL,Makeup Products (non-permanent),"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,68062,Titanium dioxide,2020-06-19,2020-06-19,NaT,2020-06-19,2020-06-19,NaT,1,NaN
114634,41524,OLD SPICE GENTLEMENS BLEND ALOE AND WILD SAGE ...,The Procter & Gamble Company,Old Spice,Bath Products,Body Washes and Soaps,656,13463-67-7,68074,Titanium dioxide,2020-06-23,2020-06-23,NaT,2020-06-23,2020-06-23,NaT,1,NaN

In [ ]:
# Checking if the new column has been added or not.
df1.head()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,SubCategory,CasId,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount,Discontinued_Month
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,6,Titanium dioxide,2009-06-17,2013-08-28,2011-02-01,2009-07-09,2009-07-09,NaT,1,2.0
1,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),889,65996-92-1,4,Distillates (coal tar),2009-07-01,2009-07-01,NaT,2009-07-01,2009-07-01,NaT,2,NaN
2,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),293,140-67-0,5,Estragole,2009-07-01,2009-07-01,NaT,2009-07-02,2009-07-02,NaT,2,NaN
3,4,PRECISION GLIMMER EYE LINER-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),46,Eyeliner/Eyebrow Pencils,656,13463-67-7,7,Titanium dioxide,2009-07-09,2013-08-28,NaT,2009-07-09,2009-07-09,NaT,1,NaN
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,Lip Gloss/Shine,656,13463-67-7,8,Titanium dioxide,2009-07-09,2013-08-28,2011-02-01,2009-07-09,2009-07-09,NaT,1,2.0

In [ ]:
# Dropping unnecessary columns for better analysing.
df1.drop(columns=['CSF','CSFId','CompanyId','PrimaryCategoryId','SubCategoryId','CasId','CasNumber'],inplace=True)

In [ ]:
# Checking if unnecessary columns are removed or not.
print(list[df1.columns])

list[Index(['CDPHId', 'ProductName', 'CompanyName', 'BrandName', 'PrimaryCategory',
       'SubCategory', 'ChemicalId', 'ChemicalName', 'InitialDateReported',
       'MostRecentDateReported', 'DiscontinuedDate', 'ChemicalCreatedAt',
       'ChemicalUpdatedAt', 'ChemicalDateRemoved', 'ChemicalCount',
       'Discontinued_Month'],
      dtype='object')]

# **Univariate Analysis**:-

In [ ]:
# 1-How many total products are reported?
df1['ProductName'].nunique()

33716

In [ ]:
# 2-How many unique companies exist?
df1['CompanyName'].nunique()

606

In [ ]:
# 3-How many unique brands are available?
df1['BrandName'].nunique()

2713

In [ ]:
# 4-How many unique chemicals are used?
df1['ChemicalName'].nunique()

123

In [ ]:
# 5-What is the distribution of products across primary categories?
df1['PrimaryCategory'].value_counts()

PrimaryCategory
Makeup Products (non-permanent)      75822
Nail Products                        15347
Skin Care Products                    7680
Sun-Related Products                  4939
Bath Products                         3463
Hair Coloring Products                1882
Hair Care Products (non-coloring)     1566
Tattoos and Permanent Makeup          1477
Personal Care Products                 765
Fragrances                             644
Oral Hygiene Products                  525
Shaving Products                       222
Baby Products                           49
Name: count, dtype: int64

In [ ]:
# 6-Which subcategories have the highest product count?
df1['SubCategory'].value_counts().head(5)

SubCategory
Lip Color - Lipsticks, Liners, and Pencils    16553
Eye Shadow                                    15744
Foundations and Bases                         14095
Nail Polish and Enamel                         9945
Lip Gloss/Shine                                8972
Name: count, dtype: int64

In [ ]:
# 7-What are the top 10 most used chemicals?
df1['ChemicalName'].value_counts().reset_index().head(10)

                                        ChemicalName  count
0                                   Titanium dioxide  93479
1  Silica, crystalline (airborne particles of res...   2816
2  Retinol/retinyl esters, when in daily dosages ...   2154
3                                               Mica   1919
4                           Butylated hydroxyanisole   1888
5                                       Carbon black   1758
6                                               Talc   1549
7                            Cocamide diethanolamine   1397
8                                  Retinyl palmitate   1181
9                                Vitamin A palmitate    971

In [ ]:
# 8-Which companies have the highest number of products?
df1['CompanyName'].value_counts().reset_index().head(10)

                           CompanyName  count
0                          L'Oreal USA   5747
1                                   S+   5165
2                                 Coty   5162
3  Revlon Consumer Product Corporation   4341
4         Bare Escentuals Beauty, Inc.   3828
5         The Procter & Gamble Company   3535
6                NYX Los Angeles, Inc.   3227
7         Charlotte Tilbury Beauty Ltd   2768
8                      Tarte Cosmetics   2497
9             Victoria's Secret Beauty   2219

In [ ]:
# 9-Which brands dominate the dataset?
df1['BrandName'].value_counts().reset_index().head(10)

                  BrandName  count
0                   SEPHORA   3621
1                       NYX   3227
2              bareMinerals   3158
3         Charlotte Tilbury   2451
4                    Revlon   2335
5                      NARS   2185
6  Victoria's Secret Beauty   2106
7                     tarte   2101
8              Sally Hansen   1834
9                  Sephora    1767

In [ ]:
# 10-What is the distribution of chemical count per product?


df1.groupby('ProductName')['ChemicalCount'].value_counts().reset_index()

                                             ProductName  ChemicalCount  count
0      " ROUGE DIOR ULTRA CARE LIQUID Flower Oil Liqu...              1     25
1      "DIOR PRESTIGE LE MICRO-FLUIDE TEINT DE ROSE M...              1      7
2                               "Hello Flawless!" SPF 15              1      8
3       "I'm Glam...Therefore I Am" -  Glamming Powder I              1      1
4                            "My dream lather" Soap 'Bar              1      2
...                                                  ...            ...    ...
34292                        watermelon brightening mask              1      1
34293                            waterproof shadow stick              1      5
34294                   winter wish list eye set palette              1      8
34295                 winter wonderglam luxe eye palette              1     23
34296          young, wild & free Amazonian clay palette              1      8

[34297 rows x 3 columns]

In [ ]:
df1['Discontinued_Month'].isnull().sum()

np.int64(101508)

In [ ]:
df1.shape

(114381, 16)

In [ ]:
# 11-What percentage of products are discontinued?


df2=df1.query(''' DiscontinuedDate != 'NaT'
''')

/tmp/ipykernel_4055/2495771687.py:4: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  df2=df1.query(''' DiscontinuedDate != 'NaT'

In [ ]:
df2[['ProductName','DiscontinuedDate']]=df2[['ProductName','DiscontinuedDate']].drop_duplicates()

/tmp/ipykernel_4055/3634441011.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[['ProductName','DiscontinuedDate']]=df2[['ProductName','DiscontinuedDate']].drop_duplicates()

In [ ]:
df3=df2[['ProductName','DiscontinuedDate']]

In [ ]:
df3['ProductName'].count()/df1['ProductName'].nunique()*100

np.float64(13.112468857515719)

In [ ]:
# 12-What is the distribution of product reporting over years?

In [ ]:
df1['MostRecentDateReported_year']=df1['MostRecentDateReported'].dt.year

In [ ]:
df1.groupby('MostRecentDateReported_year')['ProductName'].count().reset_index()

    MostRecentDateReported_year  ProductName
0                          2009         4649
1                          2010        21362
2                          2011         4497
3                          2012         3265
4                          2013        12429
5                          2014         7758
6                          2015         7065
7                          2016         8106
8                          2017         7962
9                          2018        12775
10                         2019        20776
11                         2020         3737

In [ ]:
# 13-How frequently are chemicals updated?
df1['frequently']=df1['ChemicalUpdatedAt']-df1['ChemicalCreatedAt']

In [ ]:
df1['frequently'].mean()

Timedelta('92 days 16:51:21.155086947')

In [ ]:
# 14-What is the distribution of chemical removal dates?
df4=df1.query(''' ChemicalDateRemoved !='NaT'
''')

/tmp/ipykernel_4055/1930512549.py:2: FutureWarning: The behavior of 'isin' with dtype=datetime64[ns] and castable values (e.g. strings) is deprecated. In a future version, these will not be considered matching by isin. Explicitly cast to the appropriate dtype before calling isin instead.
  df4=df1.query(''' ChemicalDateRemoved !='NaT'

In [ ]:
df4.head()

,CDPHId,ProductName,CompanyName,BrandName,PrimaryCategory,SubCategory,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount,Discontinued_Month,MostRecentDateReported_year,frequently
31,24,White Premium Lotion Soap,"GOJO Industries, Inc.",GOJO�,Personal Care Products,Hand Cleansers and Sanitizers,26,Cocamide diethanolamine,2009-07-23,2012-02-07,NaT,2009-07-23,2012-02-07,2010-12-30,0,NaN,2012,929 days
36,29,Aloe Up Lil' Kids SPF 45 Aloe Based Sunscreen ...,"Aloecare International, LLC",Aloe Up Lil' Kids SPF 45 Aloe Based Sunscreen ...,Sun-Related Products,Sunscreen (making a cosmetic claim),39,Titanium dioxide,2009-08-11,2009-08-11,NaT,2009-08-21,2009-08-21,2009-08-21,1,NaN,2009,0 days
224,71,Colorstay 12 Hour Eye Shadow Quad- rose shimme...,Revlon Consumer Product Corporation,Revlon,Makeup Products (non-permanent),Eye Shadow,78,Titanium dioxide,2009-08-26,2009-08-26,NaT,2009-08-26,2009-09-14,2009-09-14,1,NaN,2009,19 days
431,269,Elizabeth Arden Green Tea Relaxing Bubble Bath,"Elizabeth Arden, Inc.",Elizabeth Arden,Bath Products,Bubble and Foam Bath Products,281,Titanium dioxide,2009-09-01,2017-01-12,2013-05-13,2009-09-01,2009-09-25,2009-09-25,1,5.0,2017,24 days
432,269,Elizabeth Arden Green Tea Relaxing Bubble Bath,"Elizabeth Arden, Inc.",Elizabeth Arden,Bath Products,Bubble and Foam Bath Products,1875,"Retinol/retinyl esters, when in daily dosages ...",2009-09-01,2017-01-12,2013-05-13,2009-09-25,2009-09-29,2009-09-29,1,5.0,2017,4 days

In [ ]:
df4['ChemicalDateRemoved_year']=df4['ChemicalDateRemoved'].dt.year
df4['ChemicalDateRemoved_year'].value_counts().reset_index()

/tmp/ipykernel_4055/1437305957.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df4['ChemicalDateRemoved_year']=df4['ChemicalDateRemoved'].dt.year

    ChemicalDateRemoved_year  count
0                       2009    824
1                       2013    551
2                       2010    341
3                       2016    266
4                       2011    160
5                       2012    146
6                       2018    139
7                       2103    114
8                       2019    111
9                       2014    106
10                      2017     98
11                      2015     70
12                      2020     55
13                      2006      2
14                      2104      1
15                      2000      1

In [ ]:
# 15-Which categories have the most records overall?
primary_counts = df1['PrimaryCategory'].value_counts()
print('Top Primary Categories :')
print(primary_counts.head(10))

sub_category_counts = df1['SubCategory'].value_counts()
print('\nTop Subcategories :')
print(sub_category_counts.head(10))

Top Primary Categories :
PrimaryCategory
Makeup Products (non-permanent)      75822
Nail Products                        15347
Skin Care Products                    7680
Sun-Related Products                  4939
Bath Products                         3463
Hair Coloring Products                1882
Hair Care Products (non-coloring)     1566
Tattoos and Permanent Makeup          1477
Personal Care Products                 765
Fragrances                             644
Name: count, dtype: int64

Top Subcategories :
SubCategory
Lip Color - Lipsticks, Liners, and Pencils     16553
Eye Shadow                                     15744
Foundations and Bases                          14095
Nail Polish and Enamel                          9945
Lip Gloss/Shine                                 8972
Eyeliner/Eyebrow Pencils                        5948
Face Powders                                    4927
Sunscreen (making a cosmetic claim)             4557
Blushes                                         4082
Skin Moisturizers (making a cosmetic claim)     3364
Name: count, dtype: int64

In [ ]:
# 16- Which products contain the highest number of chemicals?

In [ ]:
# 17-What is the average chemical count per product?

In [ ]:
# 18-Which primary category has the highest average chemicals?
df1.head()

df1.groupby('PrimaryCategory')['ChemicalCount'].mean().reset_index().sort_values(by='ChemicalCount',ascending=False).head(1)

                 PrimaryCategory  ChemicalCount
12  Tattoos and Permanent Makeup       1.480704

In [ ]:
# 19-Which subcategory is the most chemically intensive?

In [ ]:
# 20-Which categories have the most diverse chemical usage?
df1.head()
df1.groupby('PrimaryCategory')['ChemicalName'].value_counts().reset_index()

,PrimaryCategory,ChemicalName,count
0,Baby Products,Titanium dioxide,22
1,Baby Products,Cocamide DEA,5
2,Baby Products,Cocamide diethanolamine,5
3,Baby Products,"Retinol/retinyl esters, when in daily dosages ...",4
4,Baby Products,Formaldehyde (gas),3
...,...,...,...
435,Sun-Related Products,beta-Myrcene,1
436,Tattoos and Permanent Makeup,Titanium dioxide,1113
437,Tattoos and Permanent Makeup,Carbon black,357
438,Tattoos and Permanent Makeup,"Carbon black (airborne, unbound particles of r...",6
439,Tattoos and Permanent Makeup,Propylene glycol mono-t-butyl ether,1

In [ ]:
# 21-Which subcategories are least chemically intensive?

In [ ]:
# 22-Which categories show the widest variation in chemical count?

In [ ]:
# 23-Which category has the highest number of discontinued products?

In [ ]:
# 24-Which subcategory is growing the fastest over time?
df1.groupby('')

In [ ]:
# 25-Which categories dominate the dataset share?

In [ ]:
# 26-Which company reports the most products?
company_counts = df1['CompanyName'].value_counts()
print('Top 10 companies by number of reported products :')
print(company_counts.head(10))

Top 10 companies by number of reported products :
CompanyName
L'Oreal USA                            5747
S+                                     5165
Coty                                   5162
Revlon Consumer Product Corporation    4341
Bare Escentuals Beauty, Inc.           3828
The Procter & Gamble Company           3535
NYX Los Angeles, Inc.                  3227
Charlotte Tilbury Beauty Ltd           2768
Tarte Cosmetics                        2497
Victoria's Secret Beauty               2219
Name: count, dtype: int64

In [ ]:
# 27-Which company uses the highest number of unique chemicals?

In [ ]:
# 28-Which brands have the highest product count?

In [ ]:
# 29-Which companies have the highest average chemicals per product?

In [ ]:
# 30-Which companies frequently update their product records?

In [ ]:
# 31-Which brands have the most discontinued products?

In [ ]:
# 32-Which companies dominate specific categories?

In [ ]:
# 33-Which brands show consistent product growth over time?

In [ ]:
# 34-Which companies have the highest chemical diversity?

In [ ]:
# 35-Which companies rely on fewer chemicals (simpler products)?

In [ ]:
# 36-Which chemicals are used most frequently?
chemical_counts = df1['ChemicalName'].value_counts()
print('Top 10 most frequently used chemicals :')
print(chemical_counts.head(10))

Top 10 most frequently used chemicals :
ChemicalName
Titanium dioxide                                                                                       93479
Silica, crystalline (airborne particles of respirable size)                                             2816
Retinol/retinyl esters, when in daily dosages in excess of 10,000 IU, or 3,000 retinol equivalents.     2154
Mica                                                                                                    1919
Butylated hydroxyanisole                                                                                1888
Carbon black                                                                                            1758
Talc                                                                                                    1549
Cocamide diethanolamine                                                                                 1397
Retinyl palmitate                                                                                       1181
Vitamin A palmitate                                                                                      971
Name: count, dtype: int64

In [ ]:
# 37-Which chemicals appear across the most categories?

In [ ]:
# 38-Which chemicals are category-specific?

In [ ]:
# 39-Which chemicals are most frequently removed?

In [ ]:
# 40-Which chemicals persist the longest in products?

In [ ]:
# 41-Which chemicals are newly introduced over time?

In [ ]:
# 42-Which chemicals are repeatedly reported across years?

In [ ]:
# 43-Which chemicals are used by the most companies?

In [ ]:
# 44-Which chemicals are most common in discontinued products?

In [ ]:
# 45-Which chemicals are associated with high chemical count products?

In [ ]:
# 46-How has product reporting changed over time?

In [ ]:
# 47-How has chemical usage evolved over years?

In [ ]:
# 48-Which year had the highest number of new products?

In [ ]:
# 49-Which year saw the most discontinued products?

In [ ]:
# 50-Is there a trend toward fewer chemicals per product over time?

In [ ]:
df.groupby('SubCategory')['InitialDateReported'].count().reset_index().sort_values(by='SubCategory')

                                          SubCategory  InitialDateReported
0             Acne Products (making a cosmetic claim)                  175
1                                 Aftershave Products                   80
2   Anti-Wrinkle/Anti-Aging Products (making a cos...                  922
3           Antiperspirants (making a cosmetic claim)                    3
4               Artificial Nails and Related Products                 1556
..                                                ...                  ...
84                            Teeth Cleaning Products                  376
85                           Teeth Whitening Products                  133
86                      Toilet Water/Eaux de Toilette                  116
87                                 UV Gel Nail Polish                 3136
88                                Underarm Deodorants                   40

[89 rows x 2 columns]

In [ ]:
df.head()

,CDPHId,ProductName,CSFId,CSF,CompanyId,CompanyName,BrandName,PrimaryCategoryId,PrimaryCategory,SubCategoryId,SubCategory,CasId,CasNumber,ChemicalId,ChemicalName,InitialDateReported,MostRecentDateReported,DiscontinuedDate,ChemicalCreatedAt,ChemicalUpdatedAt,ChemicalDateRemoved,ChemicalCount
0,2,ULTRA COLOR RICH EXTRA PLUMP LIPSTICK-ALL SHADES,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),53,"Lip Color - Lipsticks, Liners, and Pencils",656,13463-67-7,6,Titanium dioxide,06/17/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1
1,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),889,65996-92-1,4,Distillates (coal tar),07/01/2009,07/01/2009,NaN,07/01/2009,07/01/2009,NaN,2
2,3,Glover's Medicated Shampoo,NaN,NaN,338,J. Strickland & Co.,Glover's,18,Hair Care Products (non-coloring),25,Hair Shampoos (making a cosmetic claim),293,140-67-0,5,Estragole,07/01/2009,07/01/2009,NaN,07/02/2009,07/02/2009,NaN,2
3,4,PRECISION GLIMMER EYE LINER-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),46,Eyeliner/Eyebrow Pencils,656,13463-67-7,7,Titanium dioxide,07/09/2009,08/28/2013,NaN,07/09/2009,07/09/2009,NaN,1
4,5,AVON BRILLIANT SHINE LIP GLOSS-ALL SHADES �,NaN,NaN,4,New Avon LLC,AVON,44,Makeup Products (non-permanent),52,Lip Gloss/Shine,656,13463-67-7,8,Titanium dioxide,07/09/2009,08/28/2013,02/01/2011,07/09/2009,07/09/2009,NaN,1